name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pytest
        python -m pip install --upgrade influxdb_client
        python -m pip install --upgrade influxdb
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8 --max-line-length=250 --max-args=10 --max-statements=110 --max-branches=60 $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        pytest -v test/
